### PR TITLE
BXMSPROD-583 pmebuild.groovy script creation

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-583
please squash before merging

### CODE REVIEW

**Comment by mareknovotny** [comment]
I guess we should review this asap.

**Comment by Ginxo** [comment]
I totally agree with you @almope I would prefer to merge it now it's stable. Meanwhile I've been working on https://issues.redhat.com/browse/BXMSPROD-584
It's too hard to make any change, to test it and to make it work, that's why, do you agree @almope ?

**Comment by AntStephenson** [comment]
Looks good, one question , did you mistakenly commit the empty vars/projectlist.txt?

**Comment by Ginxo** [comment]
@AntStephenson yes I did. Removed! thanks!

**Pull request merged**
