### PR TITLE
Setup `githubscm.getGitRepositoryAuthor()`

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by lampajr** [comment]
I see there are some errors in the tests.. but they do not seem related to the change:

```
Error:  Failures: 
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, with full env:1411->JenkinsPipelineSpecification.addPipelineMocksToObjects_closure1$_closure13:513 Too many invocations for:

0 * getPipelineMock("sh")(['returnStdout': true, 'script': 'git config --get remote.origin.url | head -n 1']) >> 'REPO_URL'   (1 invocation)

Matching invocations (ordered by last occurrence):

1 * getPipelineMock("sh").call(['returnStdout':true, 'script':'git config --get remote.origin.url | head -n 1'])   <-- this triggered the error


Error:  Errors: 
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, no env:1388 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, with only COMMIT_STATUS_REPO_URL env defined:1433 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, with only COMMIT_STATUS_SHA env defined:1455 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and any other result:1593 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result ABORTED:1545 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result FAILURE:1569 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result SUCCESS:1497 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result UNSTABLE:1521 » NullPointer
Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult without test results:1617 » NullPointer
[INFO] 
Error:  Tests run: 449, Failures: 1, Errors: 9, Skipped: 0
```

**Comment by radtriste** [comment]
> I see there are some errors in the tests.. but they do not seem related to the change:
> 
> ```
> Error:  Failures: 
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, with full env:1411->JenkinsPipelineSpecification.addPipelineMocksToObjects_closure1$_closure13:513 Too many invocations for:
> 
> 0 * getPipelineMock("sh")(['returnStdout': true, 'script': 'git config --get remote.origin.url | head -n 1']) >> 'REPO_URL'   (1 invocation)
> 
> Matching invocations (ordered by last occurrence):
> 
> 1 * getPipelineMock("sh").call(['returnStdout':true, 'script':'git config --get remote.origin.url | head -n 1'])   <-- this triggered the error
> 
> 
> Error:  Errors: 
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, no env:1388 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, with only COMMIT_STATUS_REPO_URL env defined:1433 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatus default, with only COMMIT_STATUS_SHA env defined:1455 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and any other result:1593 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result ABORTED:1545 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result FAILURE:1569 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result SUCCESS:1497 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult and result UNSTABLE:1521 » NullPointer
> Error:    GithubScmSpec.[githubscm.groovy] updateGithubCommitStatusFromBuildResult without test results:1617 » NullPointer
> [INFO] 
> Error:  Tests run: 449, Failures: 1, Errors: 9, Skipped: 0
> ```

Not direct relation but still, we use the `getGitRepositoryName` in this method

**Comment by radtriste** [comment]
@lampajr please have a new look :)

**Comment by lampajr** [comment]
> @lampajr please have a new look :)

looks great!

**Review by lampajr — APPROVED** [review]

**Pull request merged**
