### PR TITLE
BXMSPROD-1090 resolveRepository modified

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1090
tested here and working https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/test/215/
we should test  flows still working.
Once we are sure I will fix project test failures

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
+1

**Review by radtriste — APPROVED** [review]
lgtm

**Review by Kevin-Mok — APPROVED** [review]
I believe you linked the wrong test job, but, I tested it [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/test/39/console). It seems to work fine with the default `kie-ci` credentials. :+1:

**Comment by Ginxo** [comment]
it breaks the PRs with sourceGroup = targetGroup. For us is only the case for dependantbot PRs, so I would merge and refactor shared-libraries more calmly. wdyt?

**Comment by radtriste** [comment]
I am ok with that

**Review by danielezonca — APPROVED** [review]
I think it is fine to proceed because scenario where sourceRepo = targetRepo is not really common

**Review by Kaitou786 — APPROVED** [review]

**Pull request merged**
