### PR TITLE
Adjust library to be compatible with ASF Jenkins

### PR DESCRIPTION
**Pull request by jstastny-cz**
Set of  changes to adjust pipeline libraries to ASF jenkins.

Needs to be squashed.

PR ensemble:
apache/incubator-kie-kogito-images#1709
kiegroup/jenkins-pipeline-shared-libraries#306
apache/incubator-kie-kogito-pipelines#1129

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by jstastny-cz** [comment]
@mareknovotny if you could nominate someone to review if this is not breaking anything.

**Review by ricardozanini — APPROVED** [review]

**Comment by jstastny-cz** [comment]
It is an option, could even be placed into kogito-pipelines repo. But putting that on critical path would push fix of kogito images pipelines even further.
We should not do a fork, but rather pick what we use and drop non-relevant things - thus the increased scope.

**Comment by mareknovotny** [comment]
just to be very clear, this is shared library for jenkins, which is used elsewhere not only for kogito. So keeping this as it is and fork it in ASF org is the best thing to not impact current non-kogito projects/pipelines.
The fork or create new repository has to be requested on ASF infra as i understand, not by anyone here.

**Comment by jstastny-cz** [comment]
Here is my simplistic attempt on trying to sort out the number of methods we might need for move/cherry-pick. There might be some false-positives coming from some of my local repos, but gives a fair idea what to start with:
```
[jstastny@IBM-PF3JSA31:~/gitrepo]$ for lib in PipelineHelper  buildChain  cloud  compile  githubscm  jira  mailer  maven  pmebuild  pnc  pullrequest  rhsaErrata  treebuild  util; do find -name 'Jenkinsfile*' -exec sed -n "s/.*\($lib\.\w*\)(.*)/\1/p" {} \; | sort | uniq; done
buildChain.getBuildChainVersionFromCompositeActionFile
cloud.cleanContainersAndImages
cloud.cleanDockerMultiplatformBuild
cloud.cleanLocalRegistry
cloud.cleanSkopeo
cloud.dockerBuildMultiPlatformImages
cloud.findFreePort
cloud.getDockerIOMirrorRegistryConfig
cloud.getReducedTag
cloud.installSkopeo
cloud.loginContainerRegistry
cloud.loginOpenShift
cloud.loginOpenshiftRegistry
cloud.makeQuayImagePublic
cloud.skopeoCopyRegistryImages
cloud.startLocalRegistry
githubscm.checkoutIfExists
githubscm.commitChanges
githubscm.commitChanges because globbing won't work.
githubscm.commitChanges, {
githubscm.commitChanges}", {
githubscm.createBranch
githubscm.createPR
githubscm.createPRWithLabels
githubscm.createPRWithLabels
githubscm.createPRWithLabels :
githubscm.createPrAsDraft
githubscm.deleteRelease
githubscm.deleteReleaseAndTag
githubscm.findAndStageNotIgnoredFiles
githubscm.findAndStageNotIgnoredFiles
githubscm.forkRepo
githubscm.getCommitHash
githubscm.getCommitHash {
githubscm.getCommitHash}"
githubscm.getLatestTag
githubscm.getPreviousTagFromVersion
githubscm.getRepositoryScm
githubscm.getTagCommitHash}
githubscm.isBranchExist {
githubscm.isReleaseExist {
githubscm.isThereAnyChanges {
githubscm.isThereAnyChanges{
githubscm.mergePR
githubscm.prepareCommitStatusInformation
githubscm.prepareCommitStatusInformationForPullRequest
githubscm.pushObject
githubscm.pushObject
githubscm.pushRemoteTag
githubscm.removeRemoteBranch
githubscm.removeRemoteBranch
githubscm.resolveRepository
githubscm.resolveRepository
githubscm.resolveRepository // TODO to change back to kiegroup:main
githubscm.setUserConfig
githubscm.squashCommits
githubscm.tagLocalAndRemoteRepository
githubscm.tagRepository
githubscm.updateGithubCommitStatus
githubscm.updateGithubCommitStatusFromBuildResult
githubscm.updateReleaseBody
mailer.buildLogScriptPR
mailer.sendEmail_failedPR
mailer.sendEmail_fixedPR
mailer.sendEmail_unstablePR
mailer.sendMarkdownTestSummaryNotification
maven.getSubmarineSettingsXmlId
maven.mvnSetVersionProperty
maven.mvnVersionsSet
maven.mvnVersionsUpdateParentAndChildModules
maven.uploadLocalArtifacts
pmebuild.checkoutProjects
pmebuild.executeBuildScript
pmebuild.getBuildConfiguration
pmebuild.getProjectConfiguration
pullrequest.getAuthorAndRepoForPr[0]
pullrequest.getAuthorAndRepoForPr[1]
pullrequest.postComment
util.archiveConsoleLog
util.calculateTargetReleaseBranch
util.cleanNode
util.generateHash}"
util.getGroup
util.getMajorMinorVersion}"
util.getMarkdownTestSummary
util.getNextVersion
util.getProjectGroupName
util.getProjectTriggeringJob[1]
util.getReleaseBranchFromVersion
util.parseVersion
```

**Comment by jstastny-cz** [comment]
Closing in favor of apache/incubator-kie-kogito-pipelines#1131

**Pull request closed without merging**
