### PR TITLE
BXMSPROD-1149 --globoff added to curl command

### PR DESCRIPTION
**Pull request by Ginxo**
error on `curl` command `curl -H 'Authorization: token ****' 'https://api.github.com/repos/kiegroup/optaweb-vehicle-routing/pulls?head=dependabot[bot]:dependabot/npm_and_yarn/optaweb-vehicle-routing-frontend/ini-1.3.7&state=open'` due to `dependabot[bot]` username (the brackets) 
```
--globoff Disable URL sequences and ranges using {} and []
```

Additionally the job `https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/ghprb-webhooks/job/optaweb-vehicle-routing` configuration has been changed.
- pipeline -> repositories -> repository URL: from `https://github.com/${ghprbPullAuthorLogin}/kogito-tooling` to `${ghprbAuthorRepoGitUrl}` to avoid problems in case the PR is not from a forked project

### CODE REVIEW

**Comment by almope** [comment]
@Ginxo I guess there's a typo about the replacement in the change description as both the original and new value use `ghprbAuthorRepoGitUrl`. Otherwise it looks good.

> pipeline -> repositories -> repository URL: from https://github.com/${ghprbAuthorRepoGitUrl}/kogito-tooling to ${ghprbAuthorRepoGitUrl} to avoid problems in case the PR is not from a forked project

**Review by almope — APPROVED** [review]
lgtm

**Review by mbiarnes — APPROVED** [review]
LGTM

**Comment by Ginxo** [comment]
> @Ginxo I guess there's a typo about the replacement in the change description as both the original and new value use `ghprbAuthorRepoGitUrl`. Otherwise it looks good.
> 
> > pipeline -> repositories -> repository URL: from [https://github.com/${ghprbAuthorRepoGitUrl}/kogito-tooling](https://github.com/$%7BghprbAuthorRepoGitUrl%7D/kogito-tooling) to ${ghprbAuthorRepoGitUrl} to avoid problems in case the PR is not from a forked project

@almope thanks, fixed

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
